### ISSUE TITLE
cross icon get wrong position when i have use multiple div show and hide

### ISSUE THREAD

**Issue by jaydipsinhparmar** [andreivictor/jquery-ui-autocomplete-with-clear-button#2]
I am using radio button for show particular div show hide. each div have autocomplete with textbox. 
at time current active div get proper position cross icon. but when i have flip div using js then 
it div autocomplete cross icon not proper position. this issue happen because when div is hide but
we have value of text box. so it take position with in hide mode.

I have attached screenshot for better clarity of my issue.
![Flights-Search-](https://user-images.githubusercontent.com/78431394/199008693-8e192a99-7cb7-4f29-90fc-a41809b6ea16.png)
![Flights-Search- (1)](https://user-images.githubusercontent.com/78431394/199008700-608a1a2d-a08f-4bbb-b424-bd9f3cb133ff.png)

you can checked in screenshot when oneway div active on page refresh then it display proper. but when i change div roundtrip
at time cross button get wrong position. 
I am using jquery ui 1.12 version.

**Comment by andreivictor** [comment]
If the cross icon is positioned using jQuery UI Position (which this plugin does by default), I think the issue is caused by it. From the docs (https://api.jqueryui.com/position/) - "jQuery UI does not support positioning of hidden elements". 
So: 
a) you would better position the cross icon button via CSS, by setting `clearButtonPosition` option to `false`. 
 or 
 b) try to initialize the autocomplete only **after** the container div becames active / visible (maybe you can hook an event - div.on(_'afterShow' , ...._ ). There's no need to attach the autocomplete to an input that is not shown on the page.

If you're not using jQuery UI Position, I need more details in order to diagnose the issue correctly.
Can you please provide an online demo with a minimal, reproducible example (jsfiddle, codepen)?

**Comment by jaydipsinhparmar** [comment]
Thanks [andreivictor](https://github.com/andreivictor),
I get reason why this issue happen because for hide div i am using display : none property so element not rendering on browser.
for this i have manage throw visibility  : visible or visibility : hideen property. also you give good suggestion when change radio button then  initialize the autocomplete only after the container div becames active.
